/*
 * This file is generated by jOOQ.
*/
package lab.kevin.db;


import javax.annotation.Generated;

import lab.kevin.db.tables.Author;
import lab.kevin.db.tables.Book;
import lab.kevin.db.tables.BookStore;
import lab.kevin.db.tables.BookToBookStore;
import lab.kevin.db.tables.Language;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SYS_IDX_SYS_PK_10102_10104 = Indexes0.SYS_IDX_SYS_PK_10102_10104;
    public static final Index SYS_IDX_FK_BOOK_AUTHOR_10119 = Indexes0.SYS_IDX_FK_BOOK_AUTHOR_10119;
    public static final Index SYS_IDX_FK_BOOK_LANGUAGE_10121 = Indexes0.SYS_IDX_FK_BOOK_LANGUAGE_10121;
    public static final Index SYS_IDX_SYS_PK_10108_10113 = Indexes0.SYS_IDX_SYS_PK_10108_10113;
    public static final Index SYS_IDX_SYS_CT_10124_10127 = Indexes0.SYS_IDX_SYS_CT_10124_10127;
    public static final Index SYS_IDX_FK_B2BS_BOOK_10136 = Indexes0.SYS_IDX_FK_B2BS_BOOK_10136;
    public static final Index SYS_IDX_FK_B2BS_BOOK_STORE_10134 = Indexes0.SYS_IDX_FK_B2BS_BOOK_STORE_10134;
    public static final Index SYS_IDX_SYS_PK_10130_10131 = Indexes0.SYS_IDX_SYS_PK_10130_10131;
    public static final Index SYS_IDX_SYS_PK_10096_10098 = Indexes0.SYS_IDX_SYS_PK_10096_10098;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SYS_IDX_SYS_PK_10102_10104 = Internal.createIndex("SYS_IDX_SYS_PK_10102_10104", Author.AUTHOR, new OrderField[] { Author.AUTHOR.ID }, true);
        public static Index SYS_IDX_FK_BOOK_AUTHOR_10119 = Internal.createIndex("SYS_IDX_FK_BOOK_AUTHOR_10119", Book.BOOK, new OrderField[] { Book.BOOK.AUTHOR_ID }, false);
        public static Index SYS_IDX_FK_BOOK_LANGUAGE_10121 = Internal.createIndex("SYS_IDX_FK_BOOK_LANGUAGE_10121", Book.BOOK, new OrderField[] { Book.BOOK.LANGUAGE_ID }, false);
        public static Index SYS_IDX_SYS_PK_10108_10113 = Internal.createIndex("SYS_IDX_SYS_PK_10108_10113", Book.BOOK, new OrderField[] { Book.BOOK.ID }, true);
        public static Index SYS_IDX_SYS_CT_10124_10127 = Internal.createIndex("SYS_IDX_SYS_CT_10124_10127", BookStore.BOOK_STORE, new OrderField[] { BookStore.BOOK_STORE.NAME }, true);
        public static Index SYS_IDX_FK_B2BS_BOOK_10136 = Internal.createIndex("SYS_IDX_FK_B2BS_BOOK_10136", BookToBookStore.BOOK_TO_BOOK_STORE, new OrderField[] { BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_ID }, false);
        public static Index SYS_IDX_FK_B2BS_BOOK_STORE_10134 = Internal.createIndex("SYS_IDX_FK_B2BS_BOOK_STORE_10134", BookToBookStore.BOOK_TO_BOOK_STORE, new OrderField[] { BookToBookStore.BOOK_TO_BOOK_STORE.NAME }, false);
        public static Index SYS_IDX_SYS_PK_10130_10131 = Internal.createIndex("SYS_IDX_SYS_PK_10130_10131", BookToBookStore.BOOK_TO_BOOK_STORE, new OrderField[] { BookToBookStore.BOOK_TO_BOOK_STORE.NAME, BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_ID }, true);
        public static Index SYS_IDX_SYS_PK_10096_10098 = Internal.createIndex("SYS_IDX_SYS_PK_10096_10098", Language.LANGUAGE, new OrderField[] { Language.LANGUAGE.ID }, true);
    }
}
